name: Deploy production

on:
  push:
    branches: [ "develop" ]
  # pull_request:
  #   branches: [ "develop" ]

jobs:
 build:
    name: Deploy to Server
    runs-on: ubuntu-latest
    steps:
      - name: executing remote ssh commands using key
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USERNAME }}
          key: ${{ secrets.SERVER_SSH_KEY }}
          post: ${{ secrets.PORT }}
          script: |
            sudo -i
            cd /www/wwwroot/${{ secrets.DOMAIN }}/duantn
            git pull
            composer update
            php artisan migrate
            php artisan tenants:artisan "migrate --path=database/migrations/tenant --database=tenant"
            php artisan optimize:clear
